server:
  port: 9047
spring:
  application:
    name: shopcart-del
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/robinmall?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
eureka:
  client:
    service-url:
      defaultZone: http://robin:robin@localhost:8761/eureka
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.robin.entity
