server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/DengAndRobin/Robinmall-config.git
          search-paths: files
          username: RobinAndDeng
          password: luo962464
eureka:
  client:
    service-url:
      defaultZone: http://robin:robin@localhost:8761/eureka