spring:
  datasource:
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/robinmall?serverTimezone=GMT&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
  redis:
    port: 6379
    host: 192.168.179.128
    database: 0


mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.robin.entity
  configuration:
    map-underscore-to-camel-case: true

redisson:
  addr:
    singleAddr:
      host: redis://192.168.179.128:6379
      database: 0

logging:
  level:
    io.swagger.models.parameters.AbstractSerializableParameter: error
